name: Close stale issues

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale because it has been open for 30 days with no activity.'
          close-issue-message: 'Closing this issue due to inactivity. Please reopen if needed.'
          days-before-stale: 1
          days-before-close: 1
          only-labels: ''  
